### ISSUE TITLE
老师好，请问纹理坐标映射到0-1

### ISSUE THREAD

**Issue by lihuaizhangfan** [caogtaa/CCBatchingTricks#2]
老师好，请问纹理坐标映射到0-1，还有从0-1映射回来的公式是怎样推导的，谢谢

**Comment by caogtaa** [comment]
https://caogtaa.github.io/2020/08/05/shader-remap-optimize/

lihu <notifications@github.com> 于2021年1月22日周五 上午11:43写道：
